import os
import pygame

class GameConstants:

    ACTUAL_SCREEN_SIZE = (0, 0)
    WINDOW_CENTER = (ACTUAL_SCREEN_SIZE[0] / 2, ACTUAL_SCREEN_SIZE[1] / 2)

    BLACK = (0, 0, 0)
    RED = (255, 0, 0)
    BEIGE = (194, 87, 72)

    MENU_PLAY = ("Play", 250)
    MENU_HIGHSCORE = ("HighScore", 400)
    MENU_EXIT = ("Exit", 550)

    GAME_MODE_SINGLE = ("Single", 200)
    GAME_MODE_MULTI = ("Multi", 400)
    HIGHSCORE = ("Highscore", 100)

    FPS = 60

    SCENE_START = 0
    SCENE_MENU = 1
    SCENE_OPTION_PLAYER_MODE = 2
    SCENE_HIGHSCORE = 3
    SCENE_PLAY_SINGLE = 4
    SCENE_PLAY_MULTI = 5
    SCENE_GAMEOVER = 6

    LOADING_TIME = 10

    GAME_MODE_SINGLE_PLAYER = 0
    GAME_MODE_MULTI_PLAYER = 1

    DIFFICULTY_EASY = 0
    DIFFICULTY_NORMAL = 1
    DIFFICULTY_HARD = 2


